// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fit_powerlaw_cpp
List fit_powerlaw_cpp(IntegerVector data, Nullable<int> x_min, double alpha_precision, std::string type);
RcppExport SEXP _poweRcpp_fit_powerlaw_cpp(SEXP dataSEXP, SEXP x_minSEXP, SEXP alpha_precisionSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_precision(alpha_precisionSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_powerlaw_cpp(data, x_min, alpha_precision, type));
    return rcpp_result_gen;
END_RCPP
}
// powerlaw_pdf_cpp
NumericVector powerlaw_pdf_cpp(IntegerVector x, double alpha, int x_min);
RcppExport SEXP _poweRcpp_powerlaw_pdf_cpp(SEXP xSEXP, SEXP alphaSEXP, SEXP x_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type x_min(x_minSEXP);
    rcpp_result_gen = Rcpp::wrap(powerlaw_pdf_cpp(x, alpha, x_min));
    return rcpp_result_gen;
END_RCPP
}
// powerlaw_cdf_cpp
NumericVector powerlaw_cdf_cpp(IntegerVector x, double alpha, int x_min);
RcppExport SEXP _poweRcpp_powerlaw_cdf_cpp(SEXP xSEXP, SEXP alphaSEXP, SEXP x_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type x_min(x_minSEXP);
    rcpp_result_gen = Rcpp::wrap(powerlaw_cdf_cpp(x, alpha, x_min));
    return rcpp_result_gen;
END_RCPP
}
// powerlaw_generate_cpp
IntegerVector powerlaw_generate_cpp(int n, double alpha, int x_min, Nullable<int> x_max);
RcppExport SEXP _poweRcpp_powerlaw_generate_cpp(SEXP nSEXP, SEXP alphaSEXP, SEXP x_minSEXP, SEXP x_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type x_max(x_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(powerlaw_generate_cpp(n, alpha, x_min, x_max));
    return rcpp_result_gen;
END_RCPP
}
// powerlaw_gof_cpp
List powerlaw_gof_cpp(IntegerVector data, Nullable<double> alpha, Nullable<int> x_min, int replicas, std::string type);
RcppExport SEXP _poweRcpp_powerlaw_gof_cpp(SEXP dataSEXP, SEXP alphaSEXP, SEXP x_minSEXP, SEXP replicasSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< int >::type replicas(replicasSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(powerlaw_gof_cpp(data, alpha, x_min, replicas, type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_poweRcpp_fit_powerlaw_cpp", (DL_FUNC) &_poweRcpp_fit_powerlaw_cpp, 4},
    {"_poweRcpp_powerlaw_pdf_cpp", (DL_FUNC) &_poweRcpp_powerlaw_pdf_cpp, 3},
    {"_poweRcpp_powerlaw_cdf_cpp", (DL_FUNC) &_poweRcpp_powerlaw_cdf_cpp, 3},
    {"_poweRcpp_powerlaw_generate_cpp", (DL_FUNC) &_poweRcpp_powerlaw_generate_cpp, 4},
    {"_poweRcpp_powerlaw_gof_cpp", (DL_FUNC) &_poweRcpp_powerlaw_gof_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_poweRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
