# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_powerlaw_cpp <- function(data, x_min = NULL, alpha_precision = 0.01, type = "left") {
    .Call(`_poweRcpp_fit_powerlaw_cpp`, data, x_min, alpha_precision, type)
}

powerlaw_pdf_cpp <- function(x, alpha, x_min = 1L) {
    .Call(`_poweRcpp_powerlaw_pdf_cpp`, x, alpha, x_min)
}

powerlaw_cdf_cpp <- function(x, alpha, x_min = 1L) {
    .Call(`_poweRcpp_powerlaw_cdf_cpp`, x, alpha, x_min)
}

powerlaw_generate_cpp <- function(n, alpha, x_min = 1L, x_max = NULL) {
    .Call(`_poweRcpp_powerlaw_generate_cpp`, n, alpha, x_min, x_max)
}

powerlaw_gof_cpp <- function(data, alpha = NULL, x_min = NULL, replicas = 1000L, type = "left") {
    .Call(`_poweRcpp_powerlaw_gof_cpp`, data, alpha, x_min, replicas, type)
}
