# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fit a discrete power-law distribution
#'
#' Estimates the exponent (alpha) and, optionally, the lower cut-off (xMin)
#' of a discrete power-law distribution using maximum likelihood and the
#' Kolmogorov-Smirnov criterion described in Clauset, Shalizi & Newman (2009).
#'
#' @param data     Integer vector of observations (positive integers).
#' @param x_min    Integer lower cut-off. If \code{NA} (default) it is
#'                 estimated from the data via KS minimisation.
#' @param alpha_precision Numeric tolerance for the alpha search
#'                 (default 0.01).
#' @param type     Distribution type: \code{"left"} (Type I, default) or
#'                 \code{"right"} (Type II, right-bounded).
#'
#' @return A named list with elements:
#'   \describe{
#'     \item{alpha}{Estimated power-law exponent.}
#'     \item{x_min}{Estimated (or supplied) lower cut-off.}
#'     \item{x_max}{Upper cut-off (maximum observed value for Type I).}
#'     \item{ks_statistic}{Kolmogorov-Smirnov goodness-of-fit statistic.}
#'     \item{standard_error}{Standard error of the alpha estimate.}
#'     \item{log_likelihood}{Log-likelihood at the estimated parameters.}
#'     \item{n_tail}{Number of observations in the power-law tail.}
#'     \item{type}{Distribution type string.}
#'     \item{valid}{Logical: \code{TRUE} if fitting succeeded.}
#'   }
#'
#' @examples
#' set.seed(42)
#' data <- sample(1:500, 200, replace = TRUE, prob = (1:500)^(-2.5))
#' result <- fit_powerlaw(data)
#' print(result$alpha)
#'
#' @export
fit_powerlaw_cpp <- function(data, x_min = NULL, alpha_precision = 0.01, type = "left") {
    .Call(`_poweRcpp_fit_powerlaw_cpp`, data, x_min, alpha_precision, type)
}

#' Discrete power-law probability density function
#'
#' Returns P(X = x) for a discrete power-law distribution with the given
#' parameters.
#'
#' @param x     Integer vector of values at which to evaluate the PMF.
#' @param alpha Power-law exponent (alpha > 1).
#' @param x_min Lower cut-off (positive integer, default 1).
#'
#' @return Numeric vector of probability mass values.
#'
#' @examples
#' powerlaw_pdf(1:10, alpha = 2.5, x_min = 1)
#'
#' @export
powerlaw_pdf_cpp <- function(x, alpha, x_min = 1L) {
    .Call(`_poweRcpp_powerlaw_pdf_cpp`, x, alpha, x_min)
}

#' Discrete power-law survival function (complementary CDF)
#'
#' Returns the survival function \eqn{P(X \geq x)} for a discrete power-law
#' distribution with the given parameters.  Note: this is the complementary
#' CDF (survival function), not the traditional CDF \eqn{P(X \leq x)}.
#'
#' @param x     Integer vector of values at which to evaluate the CDF.
#' @param alpha Power-law exponent (alpha > 1).
#' @param x_min Lower cut-off (positive integer, default 1).
#'
#' @return Numeric vector of survival-function values.
#'
#' @examples
#' powerlaw_cdf(1:10, alpha = 2.5, x_min = 1)
#'
#' @export
powerlaw_cdf_cpp <- function(x, alpha, x_min = 1L) {
    .Call(`_poweRcpp_powerlaw_cdf_cpp`, x, alpha, x_min)
}

#' Generate random samples from a discrete power-law distribution
#'
#' @param n     Number of samples to generate.
#' @param alpha Power-law exponent (alpha > 1).
#' @param x_min Lower cut-off (positive integer, default 1).
#' @param x_max Upper cut-off. If \code{NA} (default), uses \code{x_min * 1000}.
#'
#' @return Integer vector of length \code{n}.
#'
#' @examples
#' set.seed(1)
#' samples <- powerlaw_generate(100, alpha = 2.5, x_min = 1)
#' hist(samples, breaks = 20)
#'
#' @export
powerlaw_generate_cpp <- function(n, alpha, x_min = 1L, x_max = NULL) {
    .Call(`_poweRcpp_powerlaw_generate_cpp`, n, alpha, x_min, x_max)
}

#' Goodness-of-fit test for a discrete power-law distribution
#'
#' Computes a p-value for the hypothesis that \code{data} follow a discrete
#' power-law distribution using a semi-parametric bootstrap procedure
#' (Clauset, Shalizi & Newman 2009).  The bootstrap is parallelised with
#' \pkg{RcppParallel}.
#'
#' @param data     Integer vector of observations.
#' @param alpha    Power-law exponent.  If \code{NA} (default) it is estimated
#'                 from \code{data}.  When supplied together with \code{x_min},
#'                 both are used directly, skipping the fitting step.
#' @param x_min    Lower cut-off.  If \code{NA} (default) it is estimated
#'                 from \code{data}.
#' @param replicas Number of bootstrap replicas (default 1000).
#' @param type     Distribution type: \code{"left"} (default) or
#'                 \code{"right"}.
#'
#' @return A named list with elements:
#'   \describe{
#'     \item{p_value}{Bootstrap p-value.}
#'     \item{ks_statistic}{Observed KS statistic.}
#'     \item{alpha}{Alpha used for the test.}
#'     \item{x_min}{xMin used for the test.}
#'     \item{replicas}{Number of replicas used.}
#'   }
#'
#' @examples
#' \dontrun{
#' set.seed(42)
#' data <- sample(1:500, 200, replace = TRUE, prob = (1:500)^(-2.5))
#' gof  <- powerlaw_gof(data, replicas = 500)
#' print(gof$p_value)
#' }
#'
#' @export
powerlaw_gof_cpp <- function(data, alpha = NULL, x_min = NULL, replicas = 1000L, type = "left") {
    .Call(`_poweRcpp_powerlaw_gof_cpp`, data, alpha, x_min, replicas, type)
}

